# Generated by Django 3.0.3 on 2020-05-13 00:51

from django.db import migrations, models
import measure.validate_positive


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temphum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='codigo')),
                ('latitud', models.CharField(blank=True, max_length=10, null=True, verbose_name='latitud')),
                ('longitud', models.CharField(blank=True, max_length=10, null=True, verbose_name='longitud')),
                ('producto', models.CharField(max_length=30, verbose_name='producto')),
                ('area', models.IntegerField(blank=True, null=True, validators=[measure.validate_positive.validate_positive], verbose_name='area')),
            ],
        ),
    ]
